name: Build Release

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: copy .env.example .env

      - run: npm run dist:win

      - uses: actions/upload-artifact@v4
        with:
          name: Memecoin-Checker-Windows
          path: release/*.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: cp .env.example .env
      - run: npm run dist:mac
      - uses: actions/upload-artifact@v4
        with:
          name: Memecoin-Checker-Mac
          path: release/*.dmg
